// This file is generated by Slice Machine. Update with care!

import HeroSection from './HeroSection';
import WhoWeAreSection from './WhoWeAreSection';

export {
	HeroSection,
	WhoWeAreSection,
};

export const components = {
	hero_section: HeroSection,
	who_we_are_section: WhoWeAreSection,
};
